name: Build and Push Docker Image
#1
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image Build and Push 
        run: |
          commit_id=$(git rev-parse --short HEAD)
          image="${{ secrets.DOCKERHUB_USERNAME }}/calc:$commit_id"
          docker build --file Dockerfile --tag "$image" .
          docker images
          docker push "$image"
  
          image_latest="${{ secrets.DOCKER_USERNAME }}/calc:latest"
          docker tag "$image" "$image_latest"
          docker images
          docker push "$image_latest"
